config/routes.rb
Rails.application.routes.draw do
  resources :comments

  devise_for :users
  resources :links do
    member do
      put 'like', to: 'links#upvote'
      put 'dislike', to: 'links#downvote'
    end
    resources :comments
  end

  root to: 'links#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :link
end

app/models/link.rb
class Link < ApplicationRecord
  acts_as_votable
  belongs_to :user
  has_many :comments
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :links
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_comment, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!

  # GET /comments
  # GET /comments.json
  def index
    @comments = Comment.all
  end

  # GET /comments/1
  # GET /comments/1.json
  def show
  end

  # GET /comments/new
  def new
    @comment = Comment.new
  end

  # GET /comments/1/edit
  def edit
  end

  # POST /comments
  # POST /comments.json
  def create
    @link = Link.find(params[:link_id])    
    @comment = @link.comments.new(comment_params)
    @comment.user = current_user

    respond_to do |format|
      if @comment.save
        format.html { redirect_to @link, notice: 'Comment was successfully created.' }
        format.json { render :show, status: :created, location: @comment }
      else
        format.html { render :new }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /comments/1
  # PATCH/PUT /comments/1.json
  def update
    respond_to do |format|
      if @comment.update(comment_params)
        format.html { redirect_to @comment, notice: 'Comment was successfully updated.' }
        format.json { render :show, status: :ok, location: @comment }
      else
        format.html { render :edit }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /comments/1
  # DELETE /comments/1.json
  def destroy
    @comment.destroy
    respond_to do |format|
      format.html { redirect_to comments_url, notice: 'Comment was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_comment
      @comment = Comment.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def comment_params
      params.require(:comment).permit(:link_id, :body, :user_id)
    end
end

app/controllers/links_controller.rb
class LinksController < ApplicationController
  before_action :set_link, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index, :show]

  def upvote
    @link = Link.find(params[:id])
    @link.upvote_by current_user
    redirect_back(fallback_location: root_path)
  end

  def downvote
    @link = Link.find(params[:id])
    @link.downvote_from current_user
    redirect_back(fallback_location: root_path)
  end

  # GET /links
  # GET /links.json
  def index
    @links = Link.all
  end

  # GET /links/1
  # GET /links/1.json
  def show
  end

  # GET /links/new
  def new
    @link = current_user.links.build
  end

  # GET /links/1/edit
  def edit
  end

  # POST /links
  # POST /links.json
  def create
    @link = current_user.links.build(link_params)

    respond_to do |format|
      if @link.save
        format.html { redirect_to @link, notice: 'Link was successfully created.' }
        format.json { render :show, status: :created, location: @link }
      else
        format.html { render :new }
        format.json { render json: @link.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /links/1
  # PATCH/PUT /links/1.json
  def update
    respond_to do |format|
      if @link.update(link_params)
        format.html { redirect_to @link, notice: 'Link was successfully updated.' }
        format.json { render :show, status: :ok, location: @link }
      else
        format.html { render :edit }
        format.json { render json: @link.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /links/1
  # DELETE /links/1.json
  def destroy
    @link.destroy
    respond_to do |format|
      format.html { redirect_to links_url, notice: 'Link was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_link
      @link = Link.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def link_params
      params.require(:link).permit(:name, :url)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/links_helper.rb
module LinksHelper
end

app/views/comments/_form.html.erb
<%= form_with(model: comment, local: true) do |form| %>
  <% if comment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(comment.errors.count, "error") %> prohibited this comment from being saved:</h2>

      <ul>
      <% comment.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :link_id %>
    <%= form.number_field :link_id %>
  </div>

  <div class="field">
    <%= form.label :body %>
    <%= form.text_area :body %>
  </div>

  <div class="field">
    <%= form.label :user_id %>
    <%= form.text_field :user_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/comments/edit.html.erb
<h1>Editing Comment</h1>

<%= render 'form', comment: @comment %>

<%= link_to 'Show', @comment %> |
<%= link_to 'Back', comments_path %>

app/views/comments/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Comments</h1>

<table>
  <thead>
    <tr>
      <th>Link</th>
      <th>Body</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @comments.each do |comment| %>
      <tr>
        <td><%= comment.link_id %></td>
        <td><%= comment.body %></td>
        <td><%= comment.user %></td>
        <td><%= link_to 'Show', comment %></td>
        <td><%= link_to 'Edit', edit_comment_path(comment) %></td>
        <td><%= link_to 'Destroy', comment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Comment', new_comment_path %>

app/views/comments/new.html.erb
<h1>New Comment</h1>

<%= render 'form', comment: @comment %>

<%= link_to 'Back', comments_path %>

app/views/comments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Link:</strong>
  <%= @comment.link_id %>
</p>

<p>
  <strong>Body:</strong>
  <%= @comment.body %>
</p>

<p>
  <strong>User:</strong>
  <%= @comment.user %>
</p>

<%= link_to 'Edit', edit_comment_path(@comment) %> |
<%= link_to 'Back', comments_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Ruddit</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header>
      <nav class="navbar navbar-expand-sm bg-light navbar-light">
        <%= link_to 'rUddit', root_path, class: "navbar-brand" %>
        <% if user_signed_in? %>
          <nav class="navbar navbar-nav ml-auto">
            <ul class='navbar-nav'>
              <li class='nav-item'>
                <div class="container">
                  <%= link_to 'Sign out', destroy_user_session_path, class: 'nav-item', method: :delete %>
                </div>
              </li>
            </ul>
          </nav>
        <% else %>
          <nav class="navbar navbar-nav ml-auto">
            <ul class='navbar-nav'>
              <li class='nav-itiem'>
                <div class="container">
                  <%= link_to 'Login', new_user_session_path  %>
                </div>
              </li>
              <li class='nav-item'>
                <div class="container">
                  <%= link_to 'Sign up', new_user_registration_path  %>
                </div>
              </li>
            </ul>
          </nav>

            <% end %>

      </nav>
    </header>

    <div id="main_content" class="container">
      <div id="container" class="col-md-9 center-block">
        <%= yield %>
      </div>
    </div>
  </body>
</html>

app/views/links/_form.html.erb
<%= form_with(model: link, local: true) do |form| %>
  <% if link.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(link.errors.count, "error") %> prohibited this link from being saved:</h2>

      <ul>
      <% link.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name  %>
    <%= form.text_field :name, class: 'form-control' %>
  </div>

  <div class="field">
    <%= form.label :url %>
    <%= form.text_field :url, class: 'form-control' %>
  </div>

  <div class="actions mt-1">
    <%= form.submit 'Create', class: 'btn btn-primary' %>
  </div>
<% end %>

app/views/links/edit.html.erb
<h1>Editing Link</h1>

<%= render 'form', link: @link %>

<%= link_to 'Show', @link %> |
<%= link_to 'Back', links_path %>

app/views/links/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Links</h1>

<% @links.each do |link| %>
  <div class="link row clearfix rounded bg-light mt-1">
          <div>
            <p>
            <%= link_to link.name, link %>
            <br/>
            <small>
              Submitted by <%= link.user.email %> <%= time_ago_in_words(link.created_at) %> ago.
            </small>
            </p>
          </div>
          <div class="btn btn-group ml-auto">
            <div class="btn btn-default">
              <%= link_to fa_icon('thumbs-up'), like_link_path(link), method: :put %>
              <%= link.get_likes.size %>
            </div>
            <div class="btn btn-default">
              <%= link_to fa_icon('thumbs-down'), dislike_link_path(link), method: :put %>
              <%= link.get_dislikes.size %>
            </div>
          </div>
        </div>
<% end %>

<br>
  <%= link_to 'New Link', new_link_path, class: 'btn btn-primary' %>

app/views/links/new.html.erb
<h1>New Link</h1>

<%= render 'form', link: @link %>

<%= link_to 'Back', links_path %>

app/views/links/show.html.erb
<p id="notice"><%= notice %></p>
<div class="page-header">
  <%= link_to @link.name, @link.url %><br/>
  <small>
    Submitted by <%= @link.user.email %> <%= time_ago_in_words(@link.created_at) %> ago.
  </small>  
</div>
<hr>
<div class="container">
  <% @link.comments.each do |comment| %>
    <div class="rounded bg-light mt-1 mb-1">    
      <%= comment.body %>
      <br/>
      <small>
        Submitted by <%= comment.user.email %> <%= time_ago_in_words(comment.created_at) %> ago.
      </small>
    </div>
  <% end %>
</div>
<hr>
<div class="container">
  <h6>New comment:</h6>
  <%= simple_form_for([@link, Comment.new]) do |form| %>
      <%= form.input :body, class: 'form-control' %>
      <%= form.submit 'Save', class: 'btn btn-primary' %>
  <% end %>
</div>
<hr>
<div class="btn-group mt-1">
  <%= link_to 'Back', links_path, class: 'btn btn-primary' %>
<% if @link.user == current_user %>
  <%= link_to 'Edit', edit_link_path(@link), class: 'btn btn-default' %>
  <%= link_to 'Destroy', @link, class: 'btn btn-dafault', method: :delete, data: { confirm: 'Are you sure?' }  %>
<% end %>
</div>